In [2]:
import torch
import onlinehd

In [3]:
dim = 10000
n_samples = 1000
features = 100
classes = 5    

In [4]:
x = torch.randn(n_samples, features) # dummy data
y = torch.randint(0, classes, [n_samples]) # dummy data

In [12]:
x, x.shape

(tensor([[-0.2567,  0.5107,  0.2341,  ...,  0.2534,  0.5438, -0.7158],
         [-0.9419, -0.1558,  0.5933,  ...,  0.0701, -0.0306, -0.2533],
         [-1.0729, -0.9142,  1.7736,  ...,  0.4158, -0.2590, -0.0878],
         ...,
         [-0.7352, -2.5038, -3.0396,  ..., -0.2059,  2.9001,  0.6250],
         [ 0.6270,  1.3403,  0.5362,  ...,  1.4088,  1.7021,  0.9343],
         [ 1.7036,  0.3837, -0.4978,  ...,  0.7943, -1.1520,  1.6422]]),
 torch.Size([1000, 100]))

In [13]:
y, y.shape

(tensor([0, 1, 1, 2, 0, 2, 1, 3, 4, 4, 1, 1, 3, 1, 2, 4, 0, 4, 2, 2, 2, 4, 2, 0,
         2, 2, 0, 3, 0, 3, 3, 4, 1, 3, 4, 4, 0, 0, 2, 1, 0, 2, 4, 1, 0, 1, 3, 2,
         3, 3, 3, 4, 4, 2, 4, 2, 1, 3, 3, 2, 3, 0, 3, 3, 1, 2, 4, 3, 0, 4, 3, 3,
         2, 3, 3, 1, 1, 1, 2, 4, 3, 4, 2, 4, 1, 1, 0, 4, 1, 4, 1, 0, 0, 4, 1, 1,
         1, 3, 3, 3, 4, 4, 4, 2, 2, 1, 0, 3, 2, 0, 1, 1, 2, 3, 1, 0, 1, 1, 3, 4,
         2, 4, 1, 0, 1, 4, 2, 4, 4, 4, 0, 1, 1, 3, 0, 0, 4, 3, 4, 1, 0, 3, 0, 4,
         0, 2, 3, 0, 1, 1, 2, 1, 3, 4, 0, 1, 4, 1, 0, 2, 0, 0, 4, 2, 3, 4, 3, 1,
         4, 1, 1, 4, 0, 4, 3, 0, 4, 3, 4, 4, 4, 4, 0, 0, 0, 4, 3, 3, 0, 3, 1, 2,
         1, 3, 1, 2, 2, 2, 2, 1, 0, 4, 0, 2, 0, 2, 1, 3, 1, 4, 2, 3, 2, 4, 1, 1,
         1, 0, 2, 4, 2, 2, 2, 0, 3, 1, 1, 3, 3, 3, 0, 3, 4, 0, 1, 4, 3, 4, 1, 3,
         4, 4, 2, 1, 1, 2, 1, 4, 4, 4, 2, 2, 2, 0, 2, 3, 4, 0, 0, 2, 2, 4, 4, 4,
         1, 3, 2, 0, 2, 2, 2, 1, 4, 3, 1, 1, 0, 3, 3, 2, 2, 1, 1, 3, 4, 2, 1, 4,
         0, 0, 2, 0, 1, 2, 0

In [5]:
model = onlinehd.OnlineHD(classes, features, dim=dim)

if torch.cuda.is_available():
    print('Training on GPU!')
    model = model.to('cuda')
    x = x.to('cuda')
    y = y.to('cuda')

In [6]:
model.fit(x, y, epochs=10)
ypred = model(x)
ypred.size()

torch.Size([1000])

In [9]:
ypred

tensor([0, 1, 1, 2, 0, 2, 1, 3, 4, 4, 1, 1, 3, 1, 2, 4, 0, 4, 2, 2, 2, 4, 2, 0,
        2, 2, 0, 3, 0, 3, 3, 4, 1, 3, 4, 4, 0, 0, 2, 1, 0, 2, 4, 1, 0, 1, 3, 2,
        3, 3, 3, 4, 4, 2, 4, 2, 1, 3, 3, 2, 3, 0, 3, 3, 1, 2, 4, 3, 0, 4, 3, 3,
        2, 3, 3, 1, 1, 1, 2, 4, 3, 4, 2, 4, 1, 1, 0, 4, 1, 4, 1, 0, 0, 4, 1, 1,
        1, 3, 3, 3, 4, 4, 4, 2, 2, 1, 0, 3, 2, 0, 1, 1, 2, 3, 1, 0, 1, 1, 3, 4,
        2, 4, 1, 0, 1, 4, 2, 4, 4, 4, 0, 1, 1, 3, 0, 0, 4, 3, 4, 1, 0, 3, 0, 4,
        0, 2, 3, 0, 1, 1, 2, 1, 3, 4, 0, 1, 4, 1, 0, 2, 0, 0, 4, 2, 3, 4, 3, 1,
        4, 1, 1, 4, 0, 4, 3, 0, 4, 3, 4, 4, 4, 4, 0, 0, 0, 4, 3, 3, 0, 3, 1, 2,
        1, 3, 1, 2, 2, 2, 2, 1, 0, 4, 0, 2, 0, 2, 1, 3, 1, 4, 2, 3, 2, 4, 1, 1,
        1, 0, 2, 4, 2, 2, 2, 0, 3, 1, 1, 3, 3, 3, 0, 3, 4, 0, 1, 4, 3, 4, 1, 3,
        4, 4, 2, 1, 1, 2, 1, 4, 4, 4, 2, 2, 2, 0, 2, 3, 4, 0, 0, 2, 2, 4, 4, 4,
        1, 3, 2, 0, 2, 2, 2, 1, 4, 3, 1, 1, 0, 3, 3, 2, 2, 1, 1, 3, 4, 2, 1, 4,
        0, 0, 2, 0, 1, 2, 0, 2, 0, 3, 4,